### ISSUE TITLE
vitepress 文档插槽名称在哪里看到的

### ISSUE THREAD

**Issue by didoee** [Charles7c/charles7c.github.io#54]
vitepress 文档插槽名称在哪里看到的

**Comment by Charles7c** [comment]
可以在官方文档  [Theme Introduction/Extending the Default Theme/Layout Slots](https://vitepress.vuejs.org/guide/theme-introduction#extending-the-default-theme) 看 slot 介绍。

至于布局和 slot 的位置，可以看官方仓库 [theme-default/Layout.vue](https://github.com/vuejs/vitepress/blob/main/src/client/theme-default/Layout.vue)。

**Comment by didoee** [comment]
还没有Sidebar的插槽

**Comment by Charles7c** [comment]
> 还没有Sidebar的插槽

这块我暂时没有想到这个需求的使用场景，我还看到你在一些官方历史 issues 中评论了，建议你在官方 issues 中单独新提一个 feature issues，这样项目维护者评估后也好将它提升为新功能。

**Comment by didoee** [comment]
好的，感谢

**Comment by didoee** [comment]
我的目的是能够将文章标题也作为sidebar的子集去使用，我看你有pr大纲可以层级使用（不会描述了）

**Comment by Charles7c** [comment]
> 我的目的是能够将文章标题也作为sidebar的子集去使用，我看你有pr大纲可以层级使用（不会描述了）

大纲（outline）的深层级展示近期已经合并了 pr， 官方下个版本 1.0.0-alpha.14 就能用了。
你说的侧边栏（sidebar）应该是这种效果吧，好像看到过类似的 issues。
![image](https://user-images.githubusercontent.com/25446948/189334607-ad8400c5-9b6a-436e-a9a2-fddddf50e213.png)

**Comment by didoee** [comment]
是这种的，如果他提供一个作用域插槽的话，差不多就可以解决了





我的目的是能够将文章标题也作为sidebar的子集去使用，我看你有pr大纲可以层级使用（不会描述了）

大纲（outline）的深层级展示近期已经合并了 pr， 官方下个版本 1.0.0-alpha.14 就能用了。
你说的侧边栏（sidebar）应该是这种效果吧，好像看到过类似的 issues。
