### ISSUE TITLE
你好 请教下algolia是怎么配置的，我的搜索不出数据

### ISSUE THREAD

**Issue by Kai-web** [Charles7c/charles7c.github.io#67]

**Comment by Charles7c** [comment]
可以参考一下之前我写的流程：https://github.com/vuejs/vitepress/discussions/1154
![图片](https://user-images.githubusercontent.com/25446948/195987313-026811fd-7a4a-4d7d-a809-4e6bcb9225df.png)

实际这个百度一搜很多的，因为大多数的静态博客框架都支持它。
