### ISSUE TITLE
留言时候的github授权

### ISSUE THREAD

**Issue by xu4wang** [Charles7c/charles7c.github.io#76]
您的vuepress 知识库很棒！ 想登陆留言感谢下，用github登陆时候，看到如下提示：

```
This application will be able to read and write all public repository data. This includes the following:

Code
Issues
Pull requests
Wikis
Settings
Webhooks and services
Deploy keys

```

不知道授权后，是否意味着我的库都可以被写了？ 有点小担心哈。

**Comment by xu4wang** [comment]
会不会是建立GitHub app时候选择的权限太多了，按道理只要能拿到头像 email这些就够了。 

回头找时间我也试一下。

**Comment by Charles7c** [comment]
> 会不会是建立GitHub app时候选择的权限太多了，按道理只要能拿到头像 email这些就够了。
> 

之前我也没过多看这块，刚又创建测试了下，暂时没看到有设置授权限制的部分。
![image](https://user-images.githubusercontent.com/25446948/208358409-5b516c22-9974-4212-aca5-bef601b3c08f.png)
![image](https://user-images.githubusercontent.com/25446948/208358594-420ad9d1-c4ef-451f-a767-ddd61c4ca43f.png)

**Comment by xu4wang** [comment]
多谢验证，那应该是gitalk申请的权限。
