### ISSUE TITLE
大佬太牛了

### ISSUE THREAD

**Issue by acmu** [Charles7c/charles7c.github.io#79]
作为后端，居然懂这么多前端知识，我作为前端自愧不如 👍

**Comment by Charles7c** [comment]
谢谢，没有正统学过前端，看代码理解和搜索，站在众多开源项目肩膀上省了不少力气。

另外链接另一个项目在这儿 [ContiNew Admin](https://github.com/Charles7c/continew-admin/tree/dev/continew-admin-ui) ，两个项目都非常欢迎专业的前端同学在代码结构、设计和样式优化上 PR，让后来者少走些“弯路”。:smile:
