### ISSUE TITLE
👍🏻 来点个赞，博主这主题做得很好呀

### ISSUE THREAD

**Issue by ATQQ** [Charles7c/charles7c.github.io#81]
浏览了一下，Get到了不少设计上的点，后续准备参考一些加到自己的[博客主题里](https://theme.sugarat.top/) 💯 😏 

我看博主的主题没有单独抽离出来，感觉可以做成独立的主题包，不用和博客本身耦合在一起（使用的朋友升级起来相对方便点 哈哈）

**Comment by Charles7c** [comment]
转职的后端职业，快觉醒了，前端才练到 18 级。

**Comment by ATQQ** [comment]
可以 双(tou)修(学) 技能👍🏻
