### ISSUE TITLE
请问下你这个文档部署Nginx配置是什么样的？我这边刷新就没有内容了

### ISSUE THREAD

**Issue by niceduang** [Charles7c/charles7c.github.io#86]

**Comment by Charles7c** [comment]
你指的是刷新没有侧边栏吗？这个最近我也发现了，还未排查是哪个版本后出现的

**Comment by Charles7c** [comment]
我这个博客是部署在 Gitee Pages 和 GitHub Pages，没有使用 Nginx。
我另一个开源项目文档倒是部署在 Nginx（[https://doc.charles7c.top](https://doc.charles7c.top)），当时确实也遇到过刷新后有错误的情况，后来通过取消 cleanUrl 配置（目前后缀都带 .html）解决了，当时提了 issues，VitePress 官方也没给好的建议。

**Comment by 9uest** [comment]
你好，我测试关闭cleanUrl后， 后缀带html ，在当前页面刷新后，依旧未显示侧边栏， 但本地调试不会出现此问题。
